const users = [
  {
    id: 1,
    first_name: "Roberta",
    last_name: "Peele",
    email: "rpeele0@nasa.gov",
    gender: "Female",
  },
  {
    id: 2,
    first_name: "Rodrique",
    last_name: "Quant",
    email: "rquant1@rambler.ru",
    gender: "Male",
  },
  {
    id: 3,
    first_name: "Ingamar",
    last_name: "Lillie",
    email: "ilillie2@squidoo.com",
    gender: "Male",
  },
  {
    id: 4,
    first_name: "Port",
    last_name: "Thurske",
    email: "pthurske3@ihg.com",
    gender: "Male",
  },
  {
    id: 5,
    first_name: "Zedekiah",
    last_name: "Washington",
    email: "zwashington4@friendfeed.com",
    gender: "Male",
  },
  {
    id: 6,
    first_name: "Selinda",
    last_name: "Knibb",
    email: "sknibb5@parallels.com",
    gender: "Bigender",
  },
  {
    id: 7,
    first_name: "Kessiah",
    last_name: "MacNeil",
    email: "kmacneil6@go.com",
    gender: "Female",
  },
  {
    id: 8,
    first_name: "Ambros",
    last_name: "Shepperd",
    email: "ashepperd7@sakura.ne.jp",
    gender: "Male",
  },
  {
    id: 9,
    first_name: "Tedda",
    last_name: "Davydychev",
    email: "tdavydychev8@lulu.com",
    gender: "Agender",
  },
  {
    id: 10,
    first_name: "Borg",
    last_name: "Ech",
    email: "bech9@thetimes.co.uk",
    gender: "Male",
  },
  {
    id: 11,
    first_name: "Selinda",
    last_name: "Kuch bhi",
    email: "skuchbhi5@parallels.com",
    gender: "Bigender",
  },
];
return users;
